version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9092:9092
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./config/dynamic_targets.json:/etc/prometheus/dynamic_targets.json
    command: [
      "--web.listen-address=:9092",
      "--config.file=/etc/prometheus/prometheus.yml",
		  "--storage.tsdb.path=/prometheus",
      "--storage.tsdb.retention.time=30d",
		  "--web.console.libraries=/usr/share/prometheus/console_libraries",
		  "--web.console.templates=/usr/share/prometheus/consoles"
    ]