global:
  scrape_interval: 15s
  evaluation_interval: 1m

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: "web-server-1"
    static_configs:
      - targets: ["web-server-1:9090"]

  - job_name: "web-server-2"
    static_configs:
      - targets: ["web-server-2:9090"]

  - job_name: "dynamic-web-servers"
    file_sd_configs:
      - refresh_interval: 1m
        files:
          - /etc/prometheus/dynamic_targets.json